language: go
branches:
  except:
  - pre-release
  - v*
go:
  - 1.11.x
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go test
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
after_success:
  - ghr -u $GITHUB_USER -t $GITHUB_TOKEN v0.1.0 dist/